name: Create Release

# runw when a tag is created
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  contents: read

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Get Tag
      id: tag
      run: |
        if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
          echo "::set-output name=tag::${{ github.event.inputs.tag }}"
        else
          echo "::set-output name=tag::${{ github.ref }}"
        fi

    - uses: actions/checkout@v4

    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        pip install poetry==1.5.1
        poetry install --only-root

    # - name: Check versions
    #   run: |
    #     poetry verison == ${{ steps.tag.outputs.tag }}

    - name: Build wheel
      run: |
        poetry version ${{ steps.tag.outputs.tag }}
        poetry build

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./dist/*
          ./veg2hab/package_data/*
        tag_name: ${{ steps.tag.outputs.tag }}
        prerelease: false
        generate_release_notes: true
        target_commitish: ${{ github.sha }}
