name: Create Release

# runw when a tag is created
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Get Tag
      id: tag
      run: |
        if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
          echo "::set-output name=tag::${{ github.event.inputs.tag }}"
        else
          echo "::set-output name=tag::${{ github.ref_name }}"
        fi

    - uses: actions/checkout@v4

    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        pip install poetry==1.5.1
        poetry install --without dev

    - name: Check versions
      run: |
        poetry run python release.py check-versions ${{ steps.tag.outputs.tag }}

    - name: Publish release to pypi
      run: |
        poetry publish --build
      env:
        POETRY_PYPI_TOKEN_VEG2HAB: ${{ secrets.PYPI_TOKEN }}

    - name: Create github release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./dist/*
        tag_name: ${{ steps.tag.outputs.tag }}
        prerelease: false
        generate_release_notes: true
        target_commitish: ${{ github.sha }}
