name: Lint and test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-test:
    strategy:
      matrix:
        version: ["3.7", "3.8"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}

    # TODO: update poetry version (will require newer version of python)
    - name: Install dependencies
      run: |
        pip install poetry==1.5.1
        poetry install
    
    - name: Install mdbtools
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install mdbtools
    
    - name: Lint
      run: |
        poetry run black --check veg2hab
        poetry run isort --check veg2hab

    - name: Test with pytest ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        poetry run pytest -v tests --run_slow

    - name: Test with pytest windows
      if: startsWith(matrix.os, 'windows')
      run: |
        poetry run pytest -v tests --run_slow -k "not test_editable_vegtypen"

    # TODO dit zou nog een keer netjes zijn
    # - name: Pyright
    #   run: |
    #     poetry run pyright veg2hab
