name: Lint and test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-test:
    strategy:
      matrix:
        version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}

    # TODO: update poetry version (will require newer version of python)
    - name: Install dependencies
      run: |
        pip install poetry==1.8.5
        poetry install

    - name: Install mdbtools
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install mdbtools

    - name: Lint
      run: |
        poetry run black --check veg2hab
        poetry run isort --check veg2hab

    - name: Test with pytest
      run: |
        poetry run pytest -v tests --run-slow

    # TODO dit zou nog een keer netjes zijn
    # - name: Pyright
    #   run: |
    #     poetry run pyright veg2hab
